services:
  db:
    ports:
      - "5433:5432"

  influxdb:
    ports:
      - "8086:8086"

  redis:
    ports:
      - "6379:6379"

  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    depends_on:
      redis:
        condition: service_healthy

  api:
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  web:
    ports:
      - "8080:80"

volumes:
  redisinsight_data:
