sonar.projectKey=ecoterritoire
sonar.projectName=ecoterritoire
sonar.sources=app,lib,script
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.exclusions=**/__pycache__/**,**/*.pyc,client-web/**,docker/**,sql/**
sonar.coverage.exclusions=tests/**,script/**
sonar.python.coverage.reportPaths=coverage.xml
